ignore:
  field_paths:
    - CreateElasticsearchDomainInput.ElasticsearchDomainName
    - CreateElasticsearchDomainInput.ElasticsearchDomaineName
  resource_names:
    - OutboundCrossClusterSearchConnection
    - Package
